### ISSUE TITLE
Add resource for call, apply, and bind section

### ISSUE THREAD

**Issue by zeitchef** [leonardomso/33-js-concepts#108]
I'd like to suggest you add Steve Griffith's video "JS Function Methods call( ), apply( ), and bind( )" in the relevant section on call, apply and bind. I find it to be far superior in both content and quality to some of the videos currently in this list. Thanks for considering!

https://www.youtube.com/watch?v=uBdH0iB1VDM

**Comment by leonardomso** [comment]
Hi @zeitchef, please open a PR and let's add it! Seems like an amazing video!

**Comment by zeitchef** [comment]
Thanks @leonardomso! On closer inspection, I see it's already listed!
