### ISSUE TITLE
Along with the current articles and videos, add an exercises section

### ISSUE THREAD

**Issue by NicolasWebDev** [leonardomso/33-js-concepts#141]
The repo is really really insightful, but having for each concept links to exercices and questions to put into practice each concept would be really really helpful as well.

Would you be open to the idea @leonardomso?

**Comment by leonardomso** [comment]
Yes, I think this is a really great idea. We should do something like this in the future.

**Comment by NicolasWebDev** [comment]
In that case, I think that really the first step would be to add an "Exercises" section to each of the concepts with maybe one exercise or two to begin with. Once users of this repo see that there are now questions, the probability of them opening Pull Requests to add more would hugely increase. 

If you would be interested I may find the first questions for each concept and submit a PR to you. What do you say?

**Comment by leonardomso** [comment]
Yeah, sounds good!

**Comment by Vivek7038** [comment]
hey I can add Exercises section for each concepts and  also some questions for each .please assign me this projects as soon as possible i would love to contribute and implement my learnings.

**Comment by mintxdp** [comment]
How about you assign me this . I am up for adding exercise section in all those concepts.

**Comment by Poornima2003** [comment]
I have made a PR #463 can u plz review my PR !!
