### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by wang-hsoo** [leonardomso/33-js-concepts#146]

**Comment by NBalsarmi** [comment]
![image](https://user-images.githubusercontent.com/55339965/81580869-a6ccec00-93b6-11ea-89c0-e1a4d77d1802.png)

Can u help me!

**Comment by leonardomso** [comment]
@NBalsarmi your functions it's not defined on in the `home.js`file.

**Comment by NBalsarmi** [comment]
> @NBalsarmi your function it's not defined on in the `home.js`file.

I make id in html page

**Comment by leonardomso** [comment]
What you mean by "id in html page"?

**Comment by NBalsarmi** [comment]
<h1 id=“message”......
Can I sand my project
I’m jest kids like programming 
I hope help me

**Comment by NBalsarmi** [comment]
> What you mean by "id in html page"?
![image](https://user-images.githubusercontent.com/55339965/81618991-427b4e00-93f1-11ea-86cb-a30b9ba35e83.jpeg)
