### ISSUE TITLE
33 JavaScript Concepts Explained 

### ISSUE THREAD

**Issue by codingknite** [leonardomso/33-js-concepts#158]
I would like to create a repo where we use the resources herein and compile the information into readable explanations of the concepts.

![readme](https://user-images.githubusercontent.com/70036189/107142399-b8d8bc80-693f-11eb-80cf-69f5d40314eb.png)
  
I have created a [repo](https://github.com/codingknite/33-concepts-explained) where we can do this. If this sounds like a good idea and anyone would like to help, I'd like to begin Immediately.

**Comment by leonardomso** [comment]
Awesome man!

**Comment by codingknite** [comment]
Cool...let's do it then👍
