### ISSUE TITLE
Checking for the Absence of a Value in JavaScript

### ISSUE THREAD

**Issue by TomerAberbach** [leonardomso/33-js-concepts#17]
I wrote an article not too long ago about checking for the absence of a value in JavaScript. It references == vs === vs typeof and briefly mentions Prototype Inheritance when discussing `hasOwnProperty`. Because of this I am not sure what section my article would go in (which is why I didn't make a pull request) so I thought I'd just link my [article](https://tomeraberba.ch/html/post/checking-for-the-absence-of-a-value-in-javascript.html) and let you decide if/where to put the article.

**Comment by leonardomso** [comment]
Well, I think that you article could go on "== vs === vs typeof" section. Can you make a PR and include your article there? You would go like this:

* 📜 [Checking for the Absence of a Value in JavaScript — Tomer Aberbach](https://tomeraberba.ch/html/post/checking-for-the-absence-of-a-value-in-javascript.html)

**Comment by TomerAberbach** [comment]
Will do!
