### ISSUE TITLE
A minimal Website maybe a great feature :)

### ISSUE THREAD

**Issue by Korak-997** [leonardomso/33-js-concepts#170]
I really love the project and its idea , that is also why i decided to translated into my own mother language. 
Yet i think building a Website with these informations may benefit a lot more people and it would be easier to find. 

I would be happy to hear your opinions about it.

**Comment by nerdgaurish** [comment]
i am in, let me know how can we get started

**Comment by nerdgaurish** [comment]
i am in, let me know how can we get started

**Comment by leonardomso** [comment]
I'd definitely be open to create a website for 33 JavaScript concepts. How could it look though? Is there any examples of projects like this that we could look up to and get inspiration?

**Comment by husainasfak** [comment]
I am in

**Comment by Amandagne** [comment]
I'm in 👍

**Comment by devhabeeblateef** [comment]
I'm in!

**Comment by JP-GECT** [comment]
I'm in !

**Comment by Korak-997** [comment]
@husainasfak @devhabeeblateef @JP-GECT @DaanMoura @nerdgaurish @ashutosh321607 

Thanks a lot for replying , and sorry in advance that i answer too late . I just do not have enough time to check notifications and follow up the convo here on GIthub. 

I am so happy that some nice people are willing to help .

It would be much more helpful maybe if we all could discuss and plan the project so we all know where are we headed and what we want to do .

Can anyone of you suggest a platform which we can talk and plan together easily ?

**Comment by JP-GECT** [comment]
discord?????

**Comment by MaYaNkKashyap681** [comment]
I'm in.

**Comment by djaalrbkamel** [comment]
It's too important to help each other 
I'm a beginner in this new industry 
I want someone who can take the time to guide  me step by step  and suggest a little project for the beginning of the race.

**Comment by d0m00re** [comment]
Maybe create a generator with READ.ME directly.

**Comment by Karthikeya-Meesala** [comment]
Hey @leonardomso, @Korak-997, @ashutosh321607, and others!

Since Hacktoberfest has just kicked off, I think this is the perfect opportunity for us to collaborate on this. I'm fairly new to open-source myself, and this would be an excellent start for me. Let's work together to make this even more amazing and beneficial for everyone.

Looking forward to diving into this challenge with you during Hacktoberfest!

- Karthikeya

**Comment by Korak-997** [comment]
Hi to everyone,

again am really sorry for replying so late, lately i was really sick and could not really keep up.


While everyone wanted to work on the Website together, i started a repo where we all can build together.
After its ready we will then try to deploy and maybe also merge with this one.



Here is a the URL: `https://github.com/Korak-997/33JsConcepts`

Everyone is welcome to join

**Comment by Karthikeya-Meesala** [comment]
Hi @Korak-997,

Hope you are feeling much better now – your health is the top priority. Thanks for setting up the repo! 

Can you share more about the design direction and the tech stack we'll be using? I'm familiar with Figma and can provide quick design concepts for iteration.

**Comment by Korak-997** [comment]
@Karthikeya-Meesala 
i think its best to transfer the discussion to the new [Repo](https://github.com/Korak-997/33JsConcepts)
i will create an Issue their with title of design and we can discuss design stuff their.

The tech stack is simply `Jekyll` for static site generation and `scss` for styling. 
Its the easiest to setup and pass very well with the concept of Markdown and Docs like website.

The idea with Figma is really nice , you can start with it and we check and make it better with time. 

The only rule we should keep is that we will have to use **Ofiicial Javascript color pallete** for everything. Like the yellow and black will me primary colors maybe and some other colors which may look nice alone side them.

You can first start doing some design stuff on Figma and share the link in the Issue i will create, then we will see what we do next

**Comment by Karthikeya-Meesala** [comment]
Sure @Korak-997, I'll respond there from here onwards. See you there!

**Comment by Korak-997** [comment]
@MaYaNkKashyap681 @JP-GECT @DaanMoura @Amandagne

**Comment by Korak-997** [comment]
@leonardomso i started with a project. If you like you can join and later we will see if we wanna merge the repos or what we want to do with them. check the [REPO](https://github.com/Korak-997/33JsConcepts)
