### ISSUE TITLE
html elements can be rendered as standard ones

### ISSUE THREAD

**Issue by sachindra149** [leonardomso/33-js-concepts#185]
we can use HTML tags like `<p>, <li>` etc to create a better UI for the page, instead of using entities. Or as is one of the issues, a minimalistic website sounds wonderful.

**Comment by rajneesh069** [comment]
Hello, umm could you shed some more light on the issue or where can I find more info about it?

**Comment by Manideep-Maddileti** [comment]
plz assign this issue to me
