### ISSUE TITLE
Intro to Web API

### ISSUE THREAD

**Issue by foolishneo** [leonardomso/33-js-concepts#21]
Thanks for composing this list. Job nicely done!

I am just wondering if we should add an intro to Web API to the list. JS developers must know this concept. Lots of devs who have been using Javascript for a while still think of setTimeout() as native Javascript.

This is a good article for this purpose
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Introduction

**Comment by leonardomso** [comment]
Yes I think that Web APIs are a nice concept. I will be looking for some links about that and maybe in the future we could make some changes. Maybe, make a section just for APIs itself, and then put those links all in there together.
