### ISSUE TITLE
Contextualising links for each concept

### ISSUE THREAD

**Issue by medic-code** [leonardomso/33-js-concepts#223]
Whilst each concept is very much represented by a wealth of reading and video material which should cover the concept in sufficient details. I do wonder whether there's a bit of context needed for the links addressing why this link has been chosen - What is particularly good about this link ? What part of the concept does this do a good job of explaining. I'm not sure many people have the brain power or the will to read 10 articles about the same concept if there's repetition of details. 

Thanks for considering. I admit this would require quite a bit of work but might make sure that each concept is high impact in the material being displayed.

**Comment by Kota-Karthik** [comment]
Hello @medic-code 
I would like to fix this issue 
so kindly assign me this issue
Thank You : )

**Comment by medic-code** [comment]
Hi @Kota-Karthik, I'm not the maintainer of the repo, I just made this suggestion aha over a year ago. @leonardomso created the repo. For such a large change to the repo as it would effect all of the concepts if you were to do this suggestion justice, it might be worth doing for one of the concepts and opening a PR to get approval from those who contribute or from @leonardomso. 

I still stand by this idea by, there's lots of fantastic links to each concept but perhaps it needs tailored so that people can get the maximum benefit out of it.

**Comment by Kota-Karthik** [comment]
@medic-code didn't you get any reply from @leonardomso over a year?

**Comment by medic-code** [comment]
I didn’t but that’s GitHub, It needn’t be him that needs to reply anyways
to start working on it, but given the scope of change starting small seems
the most sensible. As I said if you’d like to work on it I’d start small
and open a small PR see what happens in review.
