### ISSUE TITLE
Opening the link in new window 

### ISSUE THREAD

**Issue by codewithrabeeh** [leonardomso/33-js-concepts#234]
Make every link open in a new window. So it will be more convenient to learners.

**Comment by codewithrabeeh** [comment]
If you assign me. I could do this.

**Comment by RaheemAmer** [comment]
GitHub does not include the target attribute even if you use plain HTML, so it's not a in the final HTML Anchor tag. Annoying, but OK, users can just do a CTRL+click (on Windows and Linux) or CMD+click (on MacOS) on the link, the get the same behavior.

## Source:
- https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank

**Comment by RaheemAmer** [comment]
Close #234

**Comment by codewithrabeeh** [comment]
Thanks for sharing @RaheemAmer

**Comment by RaheemAmer** [comment]
Always a pleasure ❤️

**Comment by AbhayKatoch** [comment]
Could you assign me to this please.

**Comment by UjjawalGu** [comment]
can you assign me this task I am  beginner in this coding world
