### ISSUE TITLE
Add new concept - Proxy objects

### ISSUE THREAD

**Issue by prajwalkulkarni** [leonardomso/33-js-concepts#239]
I'd like to add some great resources that teach about proxies in JavaScript as it is an important concept for every JS developer to know and is currently missing from the collection. I'd want to make this contribution under the `hacktoberfest`, could you kindly assign me this issue under `hacktober-accepted` label so that I can add some resources and references about the above mentioned concept?

**Comment by Mirza-Hassan** [comment]
@prajwalkulkarni can you please assign it to me under hacktober-accepted label
