### ISSUE TITLE
find some useful resources

### ISSUE THREAD

**Issue by rjoydip** [leonardomso/33-js-concepts#27]
BTW!  This is not an issue.  You could check my repo https://github.com/rjoydip/awesome-js-resources. Maybe it could find some useful resource from here.

Nice job :+1:

**Comment by leonardomso** [comment]
Oh, I appreciate! I'll check your repo, besides that if you want make some contribution to this repo, feel free to contribute!

**Comment by rjoydip** [comment]
Thanks. Sure, I glad to contribute.
