### ISSUE TITLE
Add Bengali Translation of this Repo

### ISSUE THREAD

**Issue by crescentpartha** [leonardomso/33-js-concepts#289]
Add `Bengali` **Translation** of this Repo

**Comment by GeeteshMehto** [comment]
Hello sir, please assign this issue to me as i already worked on this kind of project in past and has a great experience.

**Comment by AbhayKatoch** [comment]
Could you assign me to this please.

**Comment by crescentpartha** [comment]
resolve / fixes #289 by #295

**Comment by leonardomso** [comment]
We already got Bengali translation.
