### ISSUE TITLE
No top-level section for iteration.

### ISSUE THREAD

**Issue by greim** [leonardomso/33-js-concepts#3]
Iteration has lots of integrations to the language and is a powerful technique. I feel like it's quite under-utilized and maybe this list could help. Here are a couple articles:

 * http://greim.github.io/gen/dist/00-intro.html (my own article)
 * http://2ality.com/2015/02/es6-iteration.html

**Comment by leonardomso** [comment]
I'm planning to add a Iterators section soon, for now I'm just getting the feedback about what concepts should or not be on the repo. Personally I think that Iterators are a good concept and I'm planning to add it soon. 😅

**Comment by greim** [comment]
Cool. Thanks for this BTW. Really great resource.
