### ISSUE TITLE
Create more repos like this. 

### ISSUE THREAD

**Issue by prabhjotsinghchadha** [leonardomso/33-js-concepts#322]
Let's create some for typescript, react.js, graphql, mongodb, and redux.

**Comment by munnokd** [comment]
Let's create.
I will give my contribution to react,js repo.

**Comment by shalabhtayal** [comment]
Lets do it !

**Comment by wastech** [comment]
i will give contribution to typescript and mongodb

**Comment by ArslanYM** [comment]
I can help in react too

**Comment by devprotim** [comment]
> Let's create some for typescript, react.js, graphql, mongodb, and redux.

Please create one for Angular too!

**Comment by Whizkevina** [comment]
Hello,
Are you done creating it, or How can I come in?

**Comment by codrrk08** [comment]
Hey...I want to contribute as well...please let me know about the repo. I can help with ReactJs and Redux toolkit.

**Comment by yasir2002** [comment]
lemme know if anyone of you is doing

**Comment by Wavei-Haruna** [comment]
Hi, guys I want to learn more about the repo I can contribute as well in reactjs, reduxtoolkit and firebase.

**Comment by leonardomso** [comment]
This will be done in the future for other languages. Stay tuned. Closing this for now.
