### ISSUE TITLE
Broken link need to be fixed...

### ISSUE THREAD

**Issue by bosedipankar** [leonardomso/33-js-concepts#336]
[Function Scope, Block Scope and Lexical Scope ] --->  [The battle between Function Scope and Block Scope — Marius Herring]   

link :  http://www.deadcoderising.com/2017-04-11-es6-var-let-and-const-the-battle-between-function-scope-and-block-scope/

**Comment by samarjit-singh** [comment]
Hi, I want to contribute to this repo, can you please assign this task to me.

**Comment by bosedipankar** [comment]
Thanks @Rajvira10 @leonardomso
