### ISSUE TITLE
Add topic : client side storage concepts

### ISSUE THREAD

**Issue by alanJames00** [leonardomso/33-js-concepts#367]
Hello @leonardomso, I'm a passionate java-script developer looking to improve my skills and help others do it. The help this repository has done in my journey is beyond phenomenal. I'm always thankful for the amazing people of the community. As a token of my gratitude, i was considering about adding a section for "Client side storage handling such as working with local storage and session storage".

Please this issue to me.

**Comment by Robinrai2612** [comment]
Hi, @alanJames00  Could you kindly assign this issue to me? I am confident that I can make a meaningful contribution to this project.

**Comment by alanJames00** [comment]
@Robinrai2612 Sorry man. I'm halfway through the PR to be submitted. If you want any other ideas on topics or issues, let me know.

**Comment by Robinrai2612** [comment]
@alanJames00 No problem Man. Could you please create additional tasks for me to address or can we create our own issues?

**Comment by alanJames00** [comment]
@Robinrai2612 sure man, I'm currently creating a list of missing topics to be added. I will raise a bunch of issue by today evening

**Comment by We13b-MD** [comment]
Hi @Robinirai and @alanJames00 will love to collaborate and add a contribution with any additional task

**Comment by We13b-MD** [comment]
Hi @Robinirai and @alanJames00 will love to collaborate and add a contribution with any additional task
