### ISSUE TITLE
for contributing in beginner project list with ToDo App 

### ISSUE THREAD

**Issue by Hemant-Lohar** [leonardomso/33-js-concepts#370]
Hello @leonardomso, I'm a passionate Java-script developer looking to Contribute and improve my skills. I want contribute by adding the TODO App idea to the Beginner project list. 

Please this issue to me.

**Comment by devvrat011** [comment]
Hello @leonardomso . I would like to contribute in TODO app and improve my skills.
plss assign this issue to me. Thank you

**Comment by AparajitaSingh121416** [comment]
Hey  @leonardomso. I am a beginner here and am well versed with javascript. I promise to deliver the to-do app idea to this project. 
Please assign this issue to me, i will be highly grateful.

**Comment by DarshilDhandhiya** [comment]
Hello, Leonardomso I would like to do this work. Please assign me.
