### ISSUE TITLE
There is no Marathi Translation of document

### ISSUE THREAD

**Issue by dhruvchandak30** [leonardomso/33-js-concepts#376]
I have added a PR #372 
Here is the Translated ReadMe File.
https://github.com/dhruvchandak30/33-js-concepts

**Comment by Puneet-Amrutkar** [comment]
can you please assign this issue to me

**Comment by dhruvchandak30** [comment]
@Puneet-Amrutkar  I have already submitted a PR on this. Waiting for @leonardomso  To review it.

**Comment by Puneet-Amrutkar** [comment]
> @Puneet-Amrutkar I have already submitted a PR on this. Waiting for @leonardomso To review it.

yes i know but i can be assigned if anything is not according to his needs
