### ISSUE TITLE
Hindi language translation mentioned twice in README.md

### ISSUE THREAD

**Issue by Sunny-unik** [leonardomso/33-js-concepts#384]
Hindi language translation mentioned twice in README.md and both of those mentions are from different users with different repositories.

**Comment by Abhishek-jha-96** [comment]
Yes, Hindi language translation mentioned twice but only one did its job so then by Vikas Chauhan translates given list and Instruction in
![vikaschauhan_repo](https://github.com/leonardomso/33-js-concepts/assets/78265039/7ca488b1-78bb-4244-a29e-deb57d6015a8)
 Hindi language by other just open a copy of Main ReadMe.md file which is unnecessary.
Possible Solution: Removing the Other mentioned link which just open the copy of main branch which is by - Mahima Chauhan
![mahima Chauhan_repo](https://github.com/leonardomso/33-js-concepts/assets/78265039/75a715f9-faa2-4d29-abd1-568af08f4694)

/attempt
