### ISSUE TITLE
add Dependabot

### ISSUE THREAD

**Issue by Akshayp02** [leonardomso/33-js-concepts#434]
To add Dependabot to a project, create a dependabot.yml file in project root. Configure it to check for updates in project's dependencies, and set up notifications for automated pull requests. Dependabot will then help keep dependencies up-to-date, enhancing project stability and security.

**Comment by deepu2560** [comment]
What are all the data dependabot.yml contains ?

**Comment by Akshayp02** [comment]
A `dependabot.yml` file contains configuration data for Dependabot, an automated dependency management tool. It specifies details like which package managers to monitor, update schedules, and version constraints. This YAML file defines how Dependabot identifies and updates dependencies in a project, allowing users to customize the automated updating process.

**Comment by PratyushSawan** [comment]
Hi, @Akshayp02 I can see you closed this issue. Could you please check the PR which is attached to this issue?
