### ISSUE TITLE
Add interview preparation section in each tag 

### ISSUE THREAD

**Issue by Aditya9764** [leonardomso/33-js-concepts#459]
Add interview preparation section in each tag  which will help candidate to prepare for interview

**Comment by Aditya9764** [comment]
please assign label as hacktoberfest accpted so that this issue will catch candidate attension

**Comment by dhruvinvaghani001** [comment]
i want to work on this section

**Comment by marameref** [comment]
> Add interview preparation section in each tag which will help candidate to prepare for interview

hello @Aditya9764 , hope you are having a good day... i wish to work on the issue but i have a few questions which. I tried the command " git ls-remote --tags https://github.com/leonardomso/33-js-concepts" but got no response which left me a bit confused as to the tags you have in mind. I will appreciate it if u can help me clarify so i can give meaningful contribution to the issue. thanks in advance

**Comment by stenwire** [comment]
@Aditya9764 , Here is my PR: https://github.com/leonardomso/33-js-concepts/pull/460 , for this issue.

**Comment by marameref** [comment]
@Aditya9764 i have created a PR for this issue on https://github.com/leonardomso/33-js-concepts/pull/461

pls review and merge. Thank you
