### ISSUE TITLE
I want to add a new Video link under 9. Message Queue and Event Loop

### ISSUE THREAD

**Issue by kumar007ambi** [leonardomso/33-js-concepts#509]
I want to add add new Video link which helps to understands Message Queue and Event Loop,Please assign this issue to resolve @leonardomso

**Comment by StarDust130** [comment]
Can I take this? 🔥

**Comment by swarupsahu08** [comment]
hey @leonardomso can you assign this issue to me

**Comment by kumar007ambi** [comment]
@leonardomso I have participated in hactoberfest previous year also where rules states that who will raise the issue at first he will be assigned, then assigned participant will resolve the issue, if assigned person is unable to complete it then you can assign it other participant.This is is the rule if you are following the rule then it is okay, beacuses  I have raised issues another projects in hactoberfest and I will wait for tagging and assigning.
