### ISSUE TITLE
eventloop in Spanish

### ISSUE THREAD

**Issue by devrchancay** [leonardomso/33-js-concepts#53]
in this video it is explained in a simple and understandable way the eventloop would be very good to include it

https://youtu.be/Eqq2Rb7LzYE

**Comment by leonardomso** [comment]
Please make a PR to include this video on the Event Loop section, like this:

 * 📜 [Desmitificando el Event Loop (Spanish)](https://youtu.be/Eqq2Rb7LzYE)

**Comment by devrchancay** [comment]
done https://github.com/leonardomso/33-js-concepts/pull/70
