### ISSUE TITLE
Testing in Javascript

### ISSUE THREAD

**Issue by Ashwin7mak** [leonardomso/33-js-concepts#83]
It will be really helpful if we can try adding up new section for testing in javascript. That can cover topics such as testing frameworks such as Mocha, Jasmine, Jest, etc and also giving much insight on TDD and BDD, etc.

**Comment by leonardomso** [comment]
Yes, I think in the future we could do add a section about Testing. It would require some changes in the repo and take a little time but it is a good idea.

**Comment by sushforyou** [comment]
Ya sure definitely.
