### ISSUE TITLE
Translate to French

### ISSUE THREAD

**Issue by robinmetral** [leonardomso/33-js-concepts#87]
Thanks @leonardomso for the great project!

I'm starting to translate it to French over at [robinmetral/33-concepts-js](https://github.com/robinmetral/33-concepts-js) :fr::slightly_smiling_face: 

If any other _francophone_ would like to join, let me know and I'll add you as a collaborator! :tada:

**Comment by leonardomso** [comment]
Thanks Robin, I'll add a link to your French translated repo!

**Comment by robinmetral** [comment]
Translation is finished... except for the resources themselves which, of course, I can't translate!

I'll try to find some good additional French language resources :slightly_smiling_face: 

**Avis aux francophones**: j'ai besoin de votre aide pour trouver des liens en français à ajouter à la liste :fr::rocket:
