### ISSUE TITLE
Translate to Hindi

### ISSUE THREAD

**Issue by vikaschauhan** [leonardomso/33-js-concepts#88]
Thanks @leonardomso for the great project!

I'm starting to translate it to Hindi over at [https://github.com/vikaschauhan/33-js-concepts](url) 🙂

**Comment by post2seth** [comment]
Hey vikas,

great, do you need any help?? I also like to translate it in hindi.

**Comment by leonardomso** [comment]
Thanks Vikas for your contribution, I'll add a link to your Hindi translated repo!

**Comment by adarshsaraogi** [comment]
hey Vikas
Even I am also interested
